import Head from "next/head";
import { useEffect } from "react";
import Item from "~/components/Item";
import NewItem from "~/components/NewItem";
import useTodo, { TodoItem } from "~/hooks/useTodo";
// import { api } from "~/utils/api";

export default function Home() {
  // const hello = api.example.hello.useQuery({ text: "from tRPC" });

  const {
    todo,
    done,
    complete,
    markAsTodo,
    addItem,
    changeDoneItem,
    changeTodoItem,
    addlevelTodoItem,
  } = useTodo();

  useEffect(() => {
    document.body.className = "bg-charcoal-700";
  });

  const renderItems = (
    items: TodoItem[],
  ) => {
    return items.map(({ id, value, children }, index) => (
        <>
        <Item
          key={id}
          onChange={(newValue) => changeTodoItem(id, newValue)}
          onChangeStatus={() => complete(id)}
          initialValue={value}
          addLevelTodoItem={() => addlevelTodoItem(id, items[index - 1]?.id ?? undefined)} 
          />
        {children?.length > 0 && (
          <div style={{ paddingLeft: 16 }}>
            {renderItems(children)}
          </div>
        )}
        </>
    ));
  };

  return (
    <>
      <Head>
        <title>Endless Todos</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex min-h-screen flex-col">
        <div className="bg-charcoal-800 p-5 text-center">
          <h1 className="text-2xl font-bold tracking-wide text-white">
            Endless Todos
          </h1>
        </div>
        <main className="mx-auto max-w-md justify-center px-2 pt-32 text-white">
          <div className="flex flex-col gap-2 md:w-[26.5rem]">
            <NewItem onSubmit={addItem} />
            {renderItems(todo)}
            {done.map(({ id, value }, index) => (
              <Item
                key={id}
                done
                onChange={(newValue) => changeDoneItem(id, newValue)}
                onChangeStatus={() => markAsTodo(id)}
                initialValue={value}
                addLevelTodoItem={() => addlevelTodoItem(id, todo[index - 1]?.id)} 
              />
            ))}
          </div>
        </main>
      </div>
    </>
  );
}
